### ISSUE TITLE
the public key on my email-js i am directly using.

### ISSUE THREAD

**Issue by raheelhp** [emailjs-com/help#111]
the public key on my email-js i am directly using. 
i have imported import emailjs from "emailjs-com";  
emailjs
      .sendForm('service_id', 'template_id', formRef.current, {
        publicKey: 'gNFQa4SZihiiwRucp',
      })
      .then(
        () => {
          console.log('SUCCESS!');
        },
        (error) => {
          console.log('FAILED...', error.text);
        },
      );
  }; see I am directly putting public key here. but when I click on my submit button in the console it shows invalid public key instead it is being the same on email-js dashboard.

_Originally posted by @raheelhp in https://github.com/emailjs-com/help/discussions/109#discussioncomment-9548616_

**Comment by xr0master** [comment]
no issue

**Comment by raheelhp** [comment]
then why is my console.log throwing error?
