### ISSUE TITLE
react native app-not working properly

### ISSUE THREAD

**Issue by acraig11** [emailjs-com/help#150]
email template  requires two sends before filling in template contents when sending  emails.

**### _example first send_**
Hello [alan_craig@msn.com](mailto:alan_craig@msn.com),

You got a new message from :
-----------------------------------------------------------------
**### _example second send:_**
Hello [alan_craig@msn.com](mailto:alan_craig@msn.com),

You got a new message from [alan_craig@msn.com](mailto:alan_craig@msn.com):

Hi this is alan craig. I'm interested in renting a boat on 10/24/24 please call me at 803-226-4411

Best wishes,
[alan_craig@msn.com](mailto:alan_craig@msn.com)

------------------------------------------------------------------
ContactUs-1
App

**Comment by xr0master** [comment]
You should make sure that you are sending data. You may have some issues with updating the state.
Did you debug the app?

**Comment by acraig11** [comment]
The state is getting updated as shown in the second iteration of the send.  Not sure why it takes two sends to update the email though.

On Oct 18, 2024, at 8:19 AM, xr0master ***@***.***> wrote:



You should make sure that you are sending data. You may have some issues with updating the state.
Did you debug the app?

**Comment by acraig11** [comment]
Thanks for your help. I was trying to use your example code, but realized since the parent had state variables, no need to use state variables in the example code (child). It seems to be fixed now.
Alan Craig

On Oct 18, 2024, at 8:19 AM, xr0master ***@***.***> wrote:



You should make sure that you are sending data. You may have some issues with updating the state.
Did you debug the app?
