### ISSUE TITLE
200 OK code but no emails are being recieved to designated inbox

### ISSUE THREAD

**Issue by GregP-GT** [emailjs-com/help#165]
Ive set up the emailJS - it shows the a successful send and it regiestering in the dashbaord as sent but there is no trace of the delivery in M365. I did a message trace and there is nothing.. email address inbox is correct, not quarentined,  etc. any ideas ?

Thanks

**Comment by xr0master** [comment]
The recipient's address is configured in the template.

**Comment by GregP-GT** [comment]
I know.. thats what I did.  Not much help really.

I’m using another product.. worked first time.

Ta

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
