### ISSUE TITLE
SMTP with Gmail not sending email to special domains

### ISSUE THREAD

**Issue by SarakkaYouston** [emailjs-com/help#69]
Hello everybody,
I hope there will be someone who can help me with the following issue.
I used EmailJS dashboard to setup an Email Service and Email Templates, and I'm using it, with the public API key, in a custom javascript code that I have developed. It all works fine, except for the fact that emails are not been sent to emails that don't have a domain such as @gmail.com or @icloud.com or @example.com

I did a lot of tests using @example.agency  or @example.space as domains for email to send the message to, but it always isn't delivered. If I use an email with @gmail.com or @icloud.com or @example.com the email is delivered. What could be the problem?
Could that be in my code or is it related to EmailJS?

Does this happen to someone else?

Thanks in advance to anyone who could help me
Sarah

**Comment by PasticheLLC** [comment]
Hi Sarah, I think I'm having a similar issue. Do you have any info you could share?
